### ISSUE TITLE
PARAVIEW: Typos

### ISSUE THREAD

**Issue by lsawade** [uvaaland/pugeo-userguides#4]

**Comment by lsawade** [comment]
### 1.2.3: ParaView on Tigressdata
If you want to work with large amounts of data that are hosted on the Princeton University clusters, and don't want to move them to another system (desktop machine, Clover, etc.), then Tigressdata is your best bet. This is a workstation that is intended for remote visualization of `massize` data.

**Comment by uvaaland** [comment]
Typo fixed, thanks! :)
